version: "3.8"

services:
  nextjs:
    build:
      context: .
    container_name: nextjs_dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
    env_file:
      - .env # Loads environment variables from .env
    command: pnpm run dev

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword # Make sure this is set!
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
